name: Build and Test Package

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        python-version: 3.10
        activate-environment: build-env
        environment-file: environment.yml  # Optional if you have one

    - name: Install required CLI tools
      run: sudo apt-get update && sudo apt-get install -y tree

    - name: Show Directory Tree Before Build
      run: tree -L 3

    - name: Install build tools
      shell: bash -l {0}
      run: |
        pip install --upgrade pip
        pip install build

    - name: Build the Package
      shell: bash -l {0}
      run: |
        python -m build

    - name: Show Directory Tree After Build
      run: tree -L 3

    - name: Install Built Package
      shell: bash -l {0}
      run: |
        pip install dist/*.whl

    - name: Install Test Dependencies
      shell: bash -l {0}
      run: |
        pip install pytest

    - name: Run Tests with Pytest
      shell: bash -l {0}
      run: |
        pytest
