[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Python_package"
version = "0.1.0"
description = "Python packaging for MLE Training"
readme = "README.md"
authors = [{ name = "Shankar", email = "gowri.gopalakris@tigeranalytics.com" }]
license = { text = "MIT" }
dependencies = [
    "requests",  # Example dependency
    "numpy"
]

[project.urls]
Homepage = "https://github.com/Shankar-95/mle-training/Python_package"

[pypi]
export TWINE_USERNAME=__token__
export TWINE_PASSWORD=pypi-AgEIcHlwaS5vcmcCJDI2ZGZkNTQ3LWQ3NTYtNGU1Yy05NDRhLTBiNDhhODJlMGVkZgACKlszLCIwODNjNGQ5ZS0wNmY2LTRlZDAtYjY5YS05ZTY4MGYyMGJiMjYiXQAABiD-hJiQOoBDil81fGBTdJBEAJK5LkoR5uldcc3JdU1JvA
